// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title SpokeBridge
 * @dev Stores and verifies the latest identity state roots from the PortableID Hub.
 */
contract SpokeBridge {
    /// @notice The latest verified MMR State Root from the Hub.
    bytes32 public latestStateRoot;
    
    /// @notice Address of the ZK-Verifier contract (generated by Noir).
    address public verifier;
    
    /// @notice Mapping of DIDs to their revoked status on this Spoke.
    mapping(bytes32 => bool) public isRevoked;

    event RootUpdated(bytes32 indexed newRoot);
    event IdentityVerified(bytes32 indexed did);

    constructor(address _verifier) {
        verifier = _verifier;
    }

    /**
     * @notice Updates the state root after verifying a ZK-Proof of GRANDPA finality.
     * @param _newRoot The new MMR Peak Hash.
     * @param _proof The SNARK proof generated by the Off-Chain Prover.
     */
    function updateStateRoot(bytes32 _newRoot, bytes calldata _proof) external {
        // 1. Verify ZK-Proof using the UltraPlonk verifier
        // (Simplified for demo: in production, this calls a compiled Noir verifier)
        require(_proof.length > 0, "Invalid proof");
        
        latestStateRoot = _newRoot;
        emit RootUpdated(_newRoot);
    }

    /**
     * @notice Validates a user's identity membership proof against the local state root.
     * @param _did The Decentralized Identifier.
     * @param _proof The membership proof SNARK.
     */
    function verifyIdentity(bytes32 _did, bytes calldata _proof) external {
        require(latestStateRoot != bytes32(0), "Bridge not initialized");
        require(!isRevoked[_did], "Identity is revoked");
        
        // Similarly, this would call the MembershipProof verifier
        require(_proof.length > 0, "Invalid membership proof");
        
        emit IdentityVerified(_did);
    }
}
